version: "3.6"

services:

  data_collector_ms_worker:
    # Building the image
    <<: &data_collector_ms_worker
      image: "data-collector:latest"
      build:
        context: .
        dockerfile: Dockerfile
    ports:
      - "10005:10005"
